name: Create PR
description: |
  xxx
inputs:
  message:
    description: 'Message'
    required: true
    default: コミットメッセージ
outputs:
  branch:
    value: ${{ steps.pr.outputs.branch }}
    description: プルリクエストのブランチ
runs:
  using:composite
  steps:
    - id: PR
      shell: bash
      env:
        USERNAME: github-actions[bot]
        EMAIL: test@test.com
        MESSAGE: ${{ inputs.message }}
        BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
        GITHUB_TOKEN: ${{ github.token }}
  run: |
    echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
    git config --global user.name "${USERNAME}"
    git config --global user.email "${EMAIL}"
    git switch -c "${BRANCH}"
    git add .
    git commit -m "${MESSAGE}"
    git push origin "${BRANCH}"
    gh pr create --head "${BRANCH}" --title "${MESSAGE}" --body "${MESSAGE}"